# Generated by Django 5.2.1 on 2025-06-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ai_models', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='districts',
            field=models.ManyToManyField(related_name='analytics_reports', to='authentication.district'),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='analytics_reports', to='authentication.sector'),
        ),
        migrations.AddField(
            model_name='dataqualitycheck',
            name='data_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='analytics.datasource'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='authentication.district'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='analytics.aimodel'),
        ),
        migrations.AddField(
            model_name='prediction',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_predictions', to='authentication.user'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['status', 'report_type'], name='analytics_a_status_6bd317_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['generated_at', 'is_automated'], name='analytics_a_generat_29db09_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['sector', 'district'], name='analytics_p_sector_8c7292_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['created_at', 'confidence_score'], name='analytics_p_created_4ef0b1_idx'),
        ),
    ]
