# Generated by Django 5.2.1 on 2025-06-03 20:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('assigned', 'Assigned'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('comment_added', 'Comment Added'), ('status_changed', 'Status Changed'), ('severity_changed', 'Severity Changed')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('previous_value', models.CharField(blank=True, max_length=100)),
                ('new_value', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Alert Action',
                'verbose_name_plural': 'Alert Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification'), ('in_app', 'In-App Notification'), ('webhook', 'Webhook')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255)),
                ('delivery_attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Notification',
                'verbose_name_plural': 'Alert Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('source_system', models.CharField(max_length=50)),
                ('trigger_conditions', models.JSONField(default=dict, help_text='Conditions that trigger this alert')),
                ('severity_mapping', models.JSONField(default=dict, help_text='How to determine severity')),
                ('auto_assign', models.BooleanField(default=False)),
                ('auto_notify_roles', models.JSONField(blank=True, default=list)),
                ('auto_escalate_after_hours', models.IntegerField(blank=True, null=True)),
                ('max_alerts_per_hour', models.IntegerField(default=10)),
                ('cooldown_minutes', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('severity_threshold', models.CharField(choices=[('low', 'Low and above'), ('medium', 'Medium and above'), ('high', 'High and above'), ('critical', 'Critical only')], default='medium', max_length=10)),
                ('immediate_notification', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('quiet_hours_enabled', models.BooleanField(default=False)),
                ('quiet_start_time', models.TimeField(blank=True, null=True)),
                ('quiet_end_time', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Subscription',
                'verbose_name_plural': 'Alert Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('category', models.CharField(choices=[('system', 'System'), ('security', 'Security'), ('agriculture', 'Agriculture'), ('health', 'Health'), ('education', 'Education'), ('infrastructure', 'Infrastructure'), ('emergency', 'Emergency'), ('performance', 'Performance')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('default_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alert Type',
                'verbose_name_plural': 'Alert Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed'), ('escalated', 'Escalated'), ('pending', 'Pending Review')], default='active', max_length=20)),
                ('target_roles', models.JSONField(blank=True, default=list, help_text='List of user roles to notify')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all users')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_resolution_time', models.DateTimeField(blank=True, null=True)),
                ('action_required', models.BooleanField(default=False)),
                ('action_description', models.TextField(blank=True)),
                ('immediate_actions', models.TextField(blank=True, help_text='Actions to take immediately')),
                ('recommended_actions', models.TextField(blank=True, help_text='Recommended follow-up actions')),
                ('resolution_notes', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('escalation_contact', models.CharField(blank=True, max_length=100)),
                ('priority_score', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('impact_level', models.CharField(choices=[('minimal', 'Minimal Impact'), ('low', 'Low Impact'), ('moderate', 'Moderate Impact'), ('high', 'High Impact'), ('severe', 'Severe Impact')], default='moderate', max_length=20)),
                ('affected_systems', models.JSONField(blank=True, default=list)),
                ('estimated_affected_users', models.IntegerField(default=0)),
                ('users_notified', models.IntegerField(default=0)),
                ('acknowledgments', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('escalation_count', models.IntegerField(default=0)),
                ('is_automated', models.BooleanField(default=False)),
                ('auto_resolve', models.BooleanField(default=False)),
                ('auto_escalate_hours', models.IntegerField(blank=True, null=True)),
                ('source_system', models.CharField(blank=True, max_length=50)),
                ('source_identifier', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('custom_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Alert',
                'verbose_name_plural': 'System Alerts',
                'ordering': ['-created_at', '-priority_score', '-severity'],
            },
        ),
    ]
