# Generated by Django 5.2.1 on 2025-06-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriculture', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturealert',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agriculture_alerts', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='agriculturealert',
            name='districts',
            field=models.ManyToManyField(related_name='agriculture_alerts', to='authentication.district'),
        ),
        migrations.AddField(
            model_name='agriculturealert',
            name='sectors',
            field=models.ManyToManyField(blank=True, related_name='agriculture_alerts', to='authentication.sector'),
        ),
        migrations.AddField(
            model_name='agricultureextension',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extension_services', to='authentication.district'),
        ),
        migrations.AddField(
            model_name='agricultureextension',
            name='organized_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_extensions', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='agricultureextension',
            name='sectors',
            field=models.ManyToManyField(related_name='extension_services', to='authentication.sector'),
        ),
        migrations.AddField(
            model_name='agriculturetarget',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agriculture_targets', to='authentication.district'),
        ),
        migrations.AddField(
            model_name='agriculturetarget',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agriculture_targets', to='authentication.sector'),
        ),
        migrations.AddField(
            model_name='agriculturetarget',
            name='set_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='set_agriculture_targets', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperatives', to='authentication.district'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cooperatives', to='authentication.sector'),
        ),
        migrations.AddField(
            model_name='agriculturealert',
            name='target_cooperatives',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='agriculture.cooperative'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='crops_handled',
            field=models.ManyToManyField(related_name='cooperatives', to='agriculture.crop'),
        ),
        migrations.AddField(
            model_name='agriculturetarget',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='agriculture.crop'),
        ),
        migrations.AddField(
            model_name='agricultureextension',
            name='target_crops',
            field=models.ManyToManyField(related_name='extension_services', to='agriculture.crop'),
        ),
        migrations.AddField(
            model_name='agriculturealert',
            name='affected_crops',
            field=models.ManyToManyField(blank=True, related_name='alerts', to='agriculture.crop'),
        ),
        migrations.AddField(
            model_name='cropproduction',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='agriculture.crop'),
        ),
        migrations.AddField(
            model_name='cropproduction',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_productions', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='authentication.district'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='main_crops',
            field=models.ManyToManyField(related_name='main_farmers', to='agriculture.crop'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_farmers', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to='authentication.sector'),
        ),
        migrations.AddField(
            model_name='cropproduction',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='agriculture.farmer'),
        ),
        migrations.AddField(
            model_name='agricultureextension',
            name='target_farmers',
            field=models.ManyToManyField(blank=True, related_name='extension_services', to='agriculture.farmer'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_prices', to='authentication.user'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='agriculture.crop'),
        ),
        migrations.AddField(
            model_name='marketprice',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_prices', to='authentication.district'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('name', 'year')},
        ),
        migrations.AddField(
            model_name='cropproduction',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='agriculture.season'),
        ),
        migrations.AddField(
            model_name='agriculturetarget',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='agriculture.season'),
        ),
        migrations.AlterUniqueTogether(
            name='marketprice',
            unique_together={('crop', 'district', 'market_name', 'date_recorded', 'quality_grade')},
        ),
        migrations.AlterUniqueTogether(
            name='cropproduction',
            unique_together={('farmer', 'crop', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='agriculturetarget',
            unique_together={('district', 'crop', 'season', 'sector')},
        ),
    ]
